name: Build and Push Docker image

on:
  push:
    branches: ["main"]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Free disk space on runner
        run: |
          echo "=== Before cleanup ==="
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          echo "=== After cleanup ==="
          df -h

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: vars
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/ray-llm-jupyter:latest \
            -t ghcr.io/${{ github.repository_owner }}/ray-llm-jupyter:${{ steps.vars.outputs.sha }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ray-llm-jupyter:latest
          docker push ghcr.io/${{ github.repository_owner }}/ray-llm-jupyter:${{ steps.vars.outputs.sha }}
